Build a linear regression model using these values so you can then predict the price for other houses. For example, a house with 1200 sqft, 3 bedrooms, 1 floor, 40 years old.

| Size (sqft) | Number of Bedrooms  | Number of floors | Age of  Home | Price (1000s dollars)  |
| ----------------| ------------------- |----------------- |--------------|-------------- |
| 2104            | 5                   | 1                | 45           | 460           |
| 1416            | 3                   | 2                | 40           | 232           |
| 852             | 2                   | 1                | 35           | 178           |

In [5]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
import matplotx

plt.style.use(matplotx.styles.github["dark"])
np.set_printoptions(precision=2)  # reduced display precision on numpy arrays

In [6]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

#### Matrix X

$$\mathbf{X} = 
    \begin{pmatrix}
     x^{(0)}_0 & x^{(0)}_1 & \cdots & x^{(0)}_{n-1} \\
     x^{(1)}_0 & x^{(1)}_1 & \cdots & x^{(1)}_{n-1} \\
     \cdots  \\
     x^{(m-1)}_0 & x^{(m-1)}_1 & \cdots & x^{(m-1)}_{n-1}
    \end{pmatrix}
    $$

In [7]:
# data is stored in numpy array/matrix
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]
